version: '3.8'
services:
  frontend:
    build: ./frontend 
    restart: always
    hostname: frontend
    ports:
      - "3000:80"
    networks:
      - frontend
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    networks:
      - backend
      - frontend

  items:
    build: ./item
    restart: always
    hostname: items
    env_file:
      - .env
    ports:
      - "${ITEMS_SERVICE_PORT}:${ITEMS_SERVICE_PORT}"
    networks:
      - backend
    depends_on:
      - db

  mailer:
    build: ./mailer
    restart: always
    hostname: mailer
    env_file:
      - .env
    ports:
      - "${MAILER_SERVICE_PORT}:${MAILER_SERVICE_PORT}"
    networks:
      - backend

  permission:
    build: ./permission
    restart: always
    hostname: permission
    env_file:
      - .env
    ports:
      - "${PERMISSION_SERVICE_PORT}:${PERMISSION_SERVICE_PORT}"
    networks:
      - backend

  token:
    build: ./token
    restart: always
    hostname: token
    env_file:
      - .env
    ports:
      - "${TOKEN_SERVICE_PORT}:${TOKEN_SERVICE_PORT}"
    networks:
      - backend
    depends_on:
      - db

  user:
    build: ./user
    restart: always
    hostname: user
    env_file:
      - .env
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    networks:
      - backend
    depends_on:
      - mailer
      - db

  db:
    image: 'mongo:3.7'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DSN: "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@db:27017" # Usando o nome do serviço `db`
    volumes:
      - './db/data/db-files:/data/db'
      - './db/init/:/docker-entrypoint-initdb.d/'
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    name: infrastructure
    external: true
